### ISSUE TITLE
USER STORY: Admin Login

### ISSUE THREAD

**Issue by RicardoIT-Web** [RicardoIT-Web/diners-3star-restaurant#1]
As a **administrator** I can **click on the navbar and select "login"** so that I can **make a booking on behalf of a customer**

## Acceptance Criteria
1. Identify navbar on the home page
2. Click on login
3. Sign in with Admin Credentials

## Tasks
- [x] Create  Django Models, Views & Templates
- [x] Create Superuser
- [x] Create HTML and CSS for the Home page
- [x] Add HTML and CSS styling to login page
