### ISSUE TITLE
USER STORY: Make a reservation

### ISSUE THREAD

**Issue by RicardoIT-Web** [RicardoIT-Web/diners-3star-restaurant#10]
As an **authenticated User** I can **click on the navbar and select "Bookings"** so that I can **book a table**

## Acceptance Criteria
1. View navbar
2. Select bookings
3. Select date
4. Select times
5. Select number of seats
6. Add comments

## Tasks
- [x] Create models, views and templates
- [x] Add functions to avoid double bookings
- [x] Add HTML inheritance and CSS styling to this page
